name: Print Environment Variables

on:
  push:
  workflow_dispatch:

jobs:
  printenv:
    runs-on: ubuntu-latest
    environment: TEST_ENV
    steps:
      - name: Print environment variables
        env:
          MY_ENV: ${{ vars.MY_ENV }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
          REPO_ENV: ${{ vars.REPO_ENV }}
          REPO_MY_SECRET: ${{ secrets.REPO_MY_SECRET }}
        run: printenv
